### ISSUE TITLE
Voting: Wrong rank and double entries

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-nano#400] opened 2017-06-13 14:19 UTC
**v1.0.0-rc.3** on Testnet

After logging into my testnet account, clicking on voting, searching for _punkrock_, I get wrong rank and double entries.

### Expected behaviour
![grafik](https://user-images.githubusercontent.com/19614645/27086926-eb4dec70-5053-11e7-823f-873601fc699b.png)

### Actual behaviour
I searched for punkrock and got this:
![grafik](https://user-images.githubusercontent.com/19614645/27086893-d2c06e1c-5053-11e7-8c91-2b9855265ded.png)

### Steps to reproduce
Log into your testnet account, click voting, search for punkrock.

**Comment by alepop** [comment] 2017-06-13 14:42
look like peer return wrong response. [http://testnet.lisk.io:7000/api/delegates/search?offset=0&limit=100&q=punk](http://testnet.lisk.io:7000/api/delegates/search?offset=0&limit=100&q=punk)

**Comment by slaweet** [comment] 2017-06-13 14:45
There's really something wrong in the API endpoint. Other search terms do the same everything twice and rank double, e.g.: http://testnet.lisk.io:7000/api/delegates/search?offset=0&limit=100&q=joel

**Comment by Isabello** [comment] 2017-06-13 15:04
this might be an issue with the caching implementation in 0.9.0

Can you try against mainnet?

**Comment by Isabello** [comment] 2017-06-13 15:09
Confirmed this is a bug with lisk core not with lisk nano

**Comment by punkr0ck** [comment] 2017-06-13 15:09
On Mainnet I don't get any values for "rank", "approval" and "uptime". At least, there are no double entries.

**Comment by Isabello** [comment] 2017-06-13 15:10
yes those endpoints were modified in the 0.9.0 release

**Comment by Isabello** [comment] 2017-06-15 13:05
Since this is an issue with core, not with nano, and its already fixed in core, i have labeled wont-fix

I will leave it open until 0.9.0 is released so that duplicates dont get logged.

**Closed** 2017-06-24 05:27 UTC
Labels: wontfix
