### ISSUE TITLE
 login problem

### ISSUE THREAD

**Issue by DamianZaczek** [LiskHQ/lisk-nano#747] opened 2017-09-14 18:16 UTC
Hello, I copied the password that generated my wallet I can not log in ... any suggestions ? You guys count on your help regards :)

**Comment by slaweet** [comment] 2017-09-15 06:16
Hello @DamianZaczek, this is a duplicate of #599, please refer to that issue for further information on what to do.

**Closed by slaweet** 2017-09-15 06:16 UTC
Labels: duplicate, help wanted
