### ISSUE TITLE
rc2 scrolling down cause reload

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#366] opened 2017-06-08 22:06 UTC
### Expected behaviour
scrolling down transaction list should allow to do so

### Actual behaviour
scrolling down transaction list at some point causes entire view to reload, view is being reset to top, loading bar appears and transaction view is reloaded

### Steps to reproduce
scroll down transaction list on account with lots transactions

**Comment by Isabello** [comment] 2017-06-08 22:07
This is a duplicate of this issue:
https://github.com/LiskHQ/lisk-nano/issues/361

**Closed by Isabello** 2017-06-08 22:07 UTC
