### ISSUE TITLE
Weird behaviour while UI is selected

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#17] opened 2016-10-27 10:07 UTC
It's related to #15 , after generation when UI is still selected, then generation of passphrase works weird and bugged way. It would be appropriate to remove selection while any button is clicked or/and when mouse movement event occurs.

**Comment by rferro** [comment] 2016-10-31 06:00
@karek314 I could not reproduce this bug. Explain better, please.

**Comment by karek314** [comment] 2016-11-08 09:59
I have sent you video url containing this issue as well double appearing passphrase issue.

**Comment by rferro** [comment] 2016-11-29 03:10
@karek314 How did you send the video? I did not receive.

**Comment by karek314** [comment] 2016-11-29 03:41
I have asked Olivier to forward URL to you, he said he sent you.

**Comment by slaweet** [comment] 2017-03-06 11:04
@karmacoma, please add the video link to this issue

**Comment by karmacoma** [comment] 2017-03-06 11:09
@slaweet https://www.dropbox.com/s/8opk727b5meblnk/lisk_bug.mov?dl=0

**Comment by slaweet** [comment] 2017-03-06 15:45
@karek314 I don't really understand what do you mean by this issue, how is it different from #15. Can you please try a development version of Lisk Nano with fixes of #15 and #16 at http://m.liskwallet.net:8080/ and tell me if this issue is still there?

**Comment by slaweet** [comment] 2017-03-23 15:22
I'm closing this issue as it was most likely fixed with some other fixes and we couldn't reproduce it. Feel free to reopen with more details.

**Closed by slaweet** 2017-03-23 15:22 UTC
Labels: bug, medium
